version: '3.8'

services:
  worker1:
    build:
      context: ./code
      dockerfile: Dockerfile.ssh
    container_name: worker1
    networks:
      pi-net:
        aliases:
          - worker1

  worker2:
    build:
      context: ./code
      dockerfile: Dockerfile.ssh
    container_name: worker2
    networks:
      pi-net:
        aliases:
          - worker2

  master:
    image: python:3.10-slim
    volumes:
      - ./code:/app
      - ./id_rsa:/root/.ssh/id_rsa
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - pi-net

networks:
  pi-net:
