version: '3.8'

services:
  worker:
    build:
      context: ./code
    networks:
      pi-net:
        aliases:
          - worker

  master:
    build:
      context: ./code
      dockerfile: Dockerfile.master
    image: python:3.10-slim
    volumes:
      - ./code:/app
      - ./id_rsa:/root/.ssh/id_rsa
    working_dir: /app
    networks:
      pi-net:
        aliases:
          - master
    command: tail -f /dev/null

networks:
  pi-net:
