FROM python:3.10-slim

RUN apt-get update && apt-get install -y openssh-client

WORKDIR /app
COPY pi.py requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["tail", "-f", "/dev/null"]